services:
  app:
    build:
      context: .
    ports:
      - "3002:3002"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gbdserver
      - WAIT_HOSTS=db:5432
      - WAIT_TIMEOUT=300
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gbdserver
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
